set str "This is a string"
puts "The string is: $str"
puts "The length of the string is: [string length $str]" 
puts "The character at index 3 is: [string index $str 3]"
puts "The characters from index 4 through 8 are: [string range $str 4 8]"	
puts "The index of the first occurrence of letter \"i\" is: [string first i $str]"
